### PR TITLE
Reco

### PR DESCRIPTION
**Pull request by atfienberg**

### CODE REVIEW

**Comment by philippeller** [comment]
I'm happy to merge this, however I have some general comments for possible improvements:

- functions like "check bounds" and make dataframe should be put into their own modules
- I'm personally not a huge fan of the json format for cfg files, but then again preferences can vary

So let me know, i can merge now if you want?

**Comment by atfienberg** [comment]
I can make these improvements before we merge. Are you suggesting that some of these functions be moved into a reco module or modules inside of the FreeDOM project, or just a separate file inside the reco example directory? 

What is a preferable config format that you would recommend?

**Comment by philippeller** [comment]
Regarding the first: I would even suggest to move that reco.py script (and the other modules) into the freedom directory. What do you think?

Regarding cfg files: we have use the cfg/ini format (see `ConfigParser`) sometimes, which has pros and cons (it is human readable, editable and commentable as opposed to json, but objects need parsing), or we could just write `.py` files directly if the prime objective is to have dicts and such....?
At any rate, using the current jsons is also fine with me....they are quasi standard today and widespread

**Comment by atfienberg** [comment]
I've moved the reco code into the freedom directory and split it into a few modules. Most of these modules are pretty bare at the moment, but I expect they'll all be extended in the future.

I'll stick with json for now.

**Comment by philippeller** [comment]
Looking good! Happy to merge this

**Pull request merged**
